name: Build and Test

on:
  push:
    branches-ignore:
      - "main"

env:
  REACT_APP_MAP_BOX_ACCESS_TOKEN: ${{ vars.REACT_APP_MAP_BOX_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fix node space-size
        run: export NODE_OPTIONS="--max_old_space_size=4096"
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup environment
        run: npm ci
      - name: Run linters
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Project Build
        id: build
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          npm run build --if-present
        working-directory: ${{ env.BUILD_PATH }}
